SocialLibraryMVC/Models/UserFavorites.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SocialLibraryMVC.Models
{
    public class UserFavorites
    {
        [Key]
        public int Id { get; set; }
        public string User_id { get; set; }
        [ForeignKey("User_id")]
        public virtual IdentityUser? User { get; set; }

        public long ISBN_13 { get; set; }
        [ForeignKey("ISBN_13")]
        public Book Books { get; set; }
    }
}

SocialLibraryMVC/Controllers/UserFavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialLibraryMVC.Data;
using SocialLibraryMVC.Models;

namespace SocialLibraryMVC.Controllers
{
    public class UserFavoritesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserFavoritesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserFavorites
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.UserFavorites.Include(u => u.Books).Where(u => u.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: UserFavorites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserFavorites == null)
            {
                return NotFound();
            }

            var userFavorites = await _context.UserFavorites
                .Include(u => u.Books)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userFavorites == null)
            {
                return NotFound();
            }

            return View(userFavorites);
        }

        // GET: UserFavorites/Create
        [Authorize]
        public async Task<IActionResult> Create([Bind("ISBN_13")] long ISBN_13)
        {
            var userFavoritesExists = await _context.UserFavorites.Where(f => f.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value).FirstOrDefaultAsync(f => f.ISBN_13 == ISBN_13);
            if(userFavoritesExists != null)
            {
                return RedirectToAction(nameof(Delete), ISBN_13);
            }
            UserFavorites userFavorites = new UserFavorites();
            userFavorites.User_id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            userFavorites.ISBN_13 = ISBN_13;

            if (ModelState.IsValid)
            {
                _context.Add(userFavorites);
                await _context.SaveChangesAsync();
                return NoContent();
            }
            return NoContent();
            //return RedirectToAction(nameof(Index), nameof(BooksController));
            //return RedirectToAction(nameof(Create), route);
        }

        // GET: UserFavorites/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(long? ISBN_13, [Bind("inIndex")]bool inIndex = false)
        {
            if (ISBN_13 == null || _context.UserFavorites == null)
            {
                return NoContent();
            }

            var userFavorites = await _context.UserFavorites
                .Include(u => u.Books)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.ISBN_13 == ISBN_13);
            if (userFavorites == null)
            {
                return NotFound();
            }
            if (_context.UserFavorites == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UserFavorites'  is null.");
            }
            //var userFavorites = await _context.UserFavorites.Where(f => f.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value).FirstOrDefaultAsync(f => f.ISBN_13 == ISBN_13);
            if (userFavorites != null)
            {
                _context.UserFavorites.Remove(userFavorites);
            }

            await _context.SaveChangesAsync();
            if (inIndex)
                return RedirectToAction(nameof(Index));
            return NoContent();

/*            if (id == null || _context.UserFavorites == null)
            {
                return NotFound();
            }

            var userFavorites = await _context.UserFavorites
                .Include(u => u.Books)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userFavorites == null)
            {
                return NotFound();
            }

            return View(userFavorites);*/
        }

/*        // POST: UserFavorites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserFavorites == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UserFavorites'  is null.");
            }
            var userFavorites = await _context.UserFavorites.FindAsync(id);
            if (userFavorites != null)
            {
                _context.UserFavorites.Remove(userFavorites);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }*/

        private bool UserFavoritesExists(int id)
        {
          return (_context.UserFavorites?.Any(e => e.Id == id)).GetValueOrDefault();
        }


        public async Task<IActionResult> _Favorite([Bind("ISBN_13")] long ISBN_13)
        {
            string? user = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (user == null)
                return NoContent();
            ViewData["ISBN_13"] = ISBN_13;
            var userFavoritesExists = await _context.UserFavorites.Where(f => f.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value).FirstOrDefaultAsync(f => f.ISBN_13 == ISBN_13);

            if (userFavoritesExists != null)
            {
                return PartialView("_Unfavorite");
            }
            return PartialView("_Favorite");
        }
    }
}

SocialLibraryMVC/Views/UserFavorites/Index.cshtml
@model IEnumerable<SocialLibraryMVC.Models.UserFavorites>

@{
    ViewData["Title"] = "Index";
}

<div>
    <h1 style="padding-top: 15px;">Your Favorites </h1>
    
</div>
 


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Books.Cover)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books.PublishYear)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @* If the book has an image attached, take the Cover byte array and convert it into an image. If there is no image, keep the space, but don't display anything*@
                @if (item.Books.Cover != null)
                {
                    <img id="cover" style="width:150px;height:250px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(item.Books.Cover))">
                }
                else
                {
                    <img id="cover" style="width:150px;height:200px; object-fit:cover" src="">
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Books.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Books.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Books.PublishYear)
            </td>
            <td>
                <a asp-controller="UserFavorites" asp-action="Delete" asp-route-ISBN_13="@item.ISBN_13" asp-route-inIndex=true 
                onmouseover="UnfavoriteOver(this)" onmouseout="UnfavoriteOut(this)"
                style="margin-bottom: 2px; padding-left: 30px; padding-right: 30px;" class="btn btn-danger"><i class="bi bi-heart-fill"></i></a></td>
        </tr>
}
    </tbody>
</table>

SocialLibraryMVC/Views/UserFavorites/_Favorite.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a asp-controller="UserFavorites" asp-action="Create" asp-route-ISBN_13="@ViewData["ISBN_13"]" 
onclick="loadFavorite(@ViewData["ISBN_13"], this, true)" onmouseover="FavoriteOver(this)" onmouseout="FavoriteOut(this)"
style="margin-bottom: 2px; padding-left: 30px; padding-right: 30px;" class="btn btn-light" ><i class="bi bi-heart"></i></a>

SocialLibraryMVC/Views/UserFavorites/_Unfavorite.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a asp-controller="UserFavorites" asp-action="Delete" asp-route-ISBN_13="@ViewData["ISBN_13"]" 
onclick="loadFavorite(@ViewData["ISBN_13"], this, false)" onmouseover="UnfavoriteOver(this)" onmouseout="UnfavoriteOut(this)"
style="margin-bottom: 2px; padding-left: 30px; padding-right: 30px;" class="btn btn-danger"><i class="bi bi-heart-fill"></i></a>