SocialLibraryMVC/Models/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SocialLibraryMVC.Models
{
    public class Book
    {

        [Required]
        public string Title { get; set; }
        [MaxLength(1024)]
        public string Description { get; set; }
        [Display(Name = "Author")]
        public int AuthorId { get; set; }
        [ForeignKey("AuthorId")]
        public virtual Author? Authors { get; set; }
        public Genre Genre { get; set; }
        public int PublishYear { get; set; }
        [RegularExpression(@"^[0-9]{1,10}$", ErrorMessage = "ISBN-10 should be 10 integers long")]
        //
        public long? ISBN_10 { get; set; }
        // ISBN_13 should be 13 integers long, no longer and no shorter
        [RegularExpression(@"^[0-9]{13}$", ErrorMessage = "ISBN-13 should be 13 integers long")]
        [Required]
        [Key]
        // This option is so that the database doesn't generate its own ISBN_13 each time an entry is added, and lets the user add in the ISBN_13
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ISBN_13 { get; set; }
        public byte[]? Cover { get; set; }
    }

    // Certain genres have spaces, thus the display name should be different from the internal name
    public enum Genre
    {
        Fantasy, [Display(Name = "Science Fiction")]Science_Fiction, Dystopian, Action, Adventure, Mystery, Horror,
        Thriller, [Display(Name = "Historical Fiction")] Historical_Fiction, Romance, [Display(Name="Young Adult")]Young_Adult, Children,
        Autobiography, Biography, Cooking, Art, [Display(Name = "Self Help")]Self_Help, Motivational, Health, History, Hobbies, Families, Humor,
        Business, Law, Politics, Religion, Education, Travel, [Display(Name = "True Crime")]True_Crime
    }
}

SocialLibraryMVC/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialLibraryMVC.Data;
using SocialLibraryMVC.Models;

namespace SocialLibraryMVC.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AuthorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
              return _context.Authors != null ? 
                          View(await _context.Authors.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Authors'  is null.");
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var authors = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (authors == null)
            {
                return NotFound();
            }

            return View(authors);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Biography")] Author authors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(authors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(authors);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var authors = await _context.Authors.FindAsync(id);
            if (authors == null)
            {
                return NotFound();
            }
            return View(authors);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Biography")] Author authors)
        {
            if (id != authors.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(authors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorsExists(authors.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(authors);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var authors = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (authors == null)
            {
                return NotFound();
            }

            return View(authors);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Authors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Authors'  is null.");
            }
            var authors = await _context.Authors.FindAsync(id);
            if (authors != null)
            {
                _context.Authors.Remove(authors);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorsExists(int id)
        {
          return (_context.Authors?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SocialLibraryMVC/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialLibraryMVC.Data;
using SocialLibraryMVC.Models;

namespace SocialLibraryMVC.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context; 

        public ReviewsController(ApplicationDbContext context)
        {
            _context = context; 
        }


        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Reviews.OrderByDescending(r => r.Id).Where(r => r.Id > _context.Reviews.OrderBy(r => r.Id).Last().Id - 10).Include(r => r.Books).Include(r => r.User);
            var users = _context.Users;
            ViewData["CurrentUser"] = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }
            ViewData["CurrentUser"] = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return View(reviews);
        }

        // GET: Reviews/Create
        [Authorize]
        public async Task<IActionResult> Create(long? isbn_13)
        {
            var alreadyMadeReview = await _context.Reviews.Include(b => b.Books)
                .FirstOrDefaultAsync(m => m.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value);

            if(alreadyMadeReview != null && alreadyMadeReview.Isbn_13 == isbn_13)
            {
                string redirect = nameof(Edit) + "?Id=" + alreadyMadeReview.Id;
                return RedirectToAction(nameof(Edit), alreadyMadeReview);
            }
            //ViewData["User_id"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id");
            if (isbn_13 == null || _context.Books == null)
            {
                return NotFound();
            }
            var reviews = await _context.Books
                .Include(b => b.Authors)
                .FirstOrDefaultAsync(m => m.ISBN_13 == isbn_13);
            if(reviews == null)
            {
                return NotFound();
            }
            ViewData["ISBN_13"] = isbn_13;
            ViewData["User_id"] = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Text_review,Rating,Isbn_13,User_id")] Review reviews)
        {
            //reviews.User_id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (ModelState.IsValid)
            {
                _context.Add(reviews);
                await _context.SaveChangesAsync();
                TempData["success"] = "Review created successfully!!"; //Toastr
                return RedirectToAction(nameof(Index));
            }
            ViewData["User_id"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", reviews.User_id);
            return View(reviews);
        }

        // GET: Reviews/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews.FindAsync(id);
            if (reviews == null)
            {
                return NotFound();
            }
            if (!IsAuthorized(reviews.User_id))
            {
                return RedirectToAction(nameof(Index));
            }
            ViewData["User_id"] = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["ISBN_13"] = reviews.Isbn_13;
            return View(reviews);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,User_id,Text_review,Rating,Isbn_13")] Review reviews)
        {
            if (id != reviews.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reviews);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Review edited successfully!!"; //Toastr
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewsExists(reviews.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["User_id"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", reviews.User_id);
            return View(reviews);
        }

        // GET: Reviews/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }

            if(!IsAuthorized(reviews.User_id))
            {
                return RedirectToAction(nameof(Index));
            }

            return View(reviews);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reviews == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Reviews'  is null.");
            }
            var reviews = await _context.Reviews.FindAsync(id);
            if (reviews != null)
            {
                if (!IsAuthorized(reviews.User_id))
                {
                    return RedirectToAction(nameof(Index));
                }
                _context.Reviews.Remove(reviews);
            }
            
            await _context.SaveChangesAsync();
            TempData["success"] = "Review deleted successfully!!"; //Toastr
            return RedirectToAction(nameof(Index));
        }

        // GET: Reviews/_BookReviews
        // Partial View that should appear below the Details page of a particular book. Reviews shown should only be the reviews of the chosen book
        public async Task<IActionResult> _BookReviews(long isbn_13)
        {
            var applicationDbContext = _context.Reviews.Include(r => r.Books).Include(r => r.User).Where(b => b.Isbn_13 == isbn_13);
            return PartialView(await applicationDbContext.ToListAsync());
        }

        private bool ReviewsExists(int id)
        {
          return (_context.Reviews?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private bool IsAuthorized(string user_id)
        {
            if (user_id != User.FindFirst(ClaimTypes.NameIdentifier).Value)
            {
                return false;
            }
            return true;
        }
    }
}

SocialLibraryMVC/Views/Books/Create.cshtml
@model SocialLibraryMVC.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1 style="padding-top: 15px;">Create A New Book Entry</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" >
                </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
                <!--<input asp-for="AuthorId" class="form-control" />-->
                <span asp-validation-for="AuthorId" class="text-danger"></span>
                <!-- Link to Create new Author if author is not in list -->
                <a asp-controller="Authors" asp-action="Create">Add New Author</a>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" asp-items="Html.GetEnumSelectList<Genre>().OrderBy(p => p.Text)" class="form-control"></select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishYear" class="control-label"></label>
                <input asp-for="PublishYear" class="form-control" />
                <span asp-validation-for="PublishYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN_10" class="control-label"></label>
                <input asp-for="ISBN_10" class="form-control" />
                <span asp-validation-for="ISBN_10" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN_13" class="control-label"></label>
                <input asp-for="ISBN_13" class="form-control" />
                <span asp-validation-for="ISBN_13" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" type="file" name="image" accept=".png,.jpg,.jpeg" class="form-control" onchange="document.getElementById('cover').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div>
                
                @if (ViewBag.Cover != null)
                {
                    <img id="cover" style="width:150px;height:250px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(ViewBag.Cover))">
                }
                else
                {
                    <img id="cover" style="width:150px;height:250px; object-fit:cover" src="">
                }
            </div>
            <div class="form-group" style="margin-bottom: 25px">
                <input type="submit" value="Create" class="btn btn-default" /> |
                <a asp-action="Index" class="btn btn-default">Back to List</a>
            </div>
            <div class="form-group">
                &nbsp;
                &nbsp;
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SocialLibraryMVC/Views/Books/Delete.cshtml
@model SocialLibraryMVC.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1 style="padding-top: 15px;">Delete</h1>

<h3>Are You Sure You Want to Delete This Book?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Authors.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN_10)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN_10)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dd class = "col-sm-10">
            @if (ViewBag.Cover != null)
            {
                <img id="cover" style="width:150px;height:250px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(ViewBag.Cover))">
            }
            else
            {
                <img id="cover" style="width:150px;height:250px; object-fit:cover" src="">
            }
            @*@Html.DisplayFor(model => model.Cover)*@
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ISBN_13" />
        <div style="margin-bottom: 25px">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            <a asp-action="Index" input class="btn btn-default">Back to List</a>
        </div>
    </form>
    <div class="form-group">
        &nbsp;
        &nbsp;
    </div>
</div>

SocialLibraryMVC/Views/Books/Index.cshtml
@model PaginatedList<SocialLibraryMVC.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1 style="text-align:center; padding-top:10px; padding-bottom:20px;">Welcome to the Social Library!</h1>

@*Search bar with search, back to full list, and create new book entry buttons*@
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <center>
            @*Search bar*@
        <p style="padding-top: 5px;">
            Find by Name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <input type="submit" value = "Search" class="btn btn-default" style="padding-bottom:10px"/> |
                <a asp-action="Index" class="btn btn-default" style="padding-bottom:10px">Back to Full List</a>
                <a asp-action="Create" input class="btn btn-primary" style="position:relative; margin-sm: 550px;"> <strong class="bi bi-plus-circle"  style="display:flex;align-items:center">&nbsp; Create New Book Entry</strong>  </a>
        </p>
        </center>
    </div>
</form>

@*Table for the headings of each column. Title and Author titles have filtering functionality*@
<table class="table">
    <thead style="text-align:center;"> 
        <tr>
            <th style="text-align:center;">
                Cover
            </th>
            <th style="text-align:center;">
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Title</a>
            </th>
            <th style="text-align:center;">
                Description
            </th>
            <th style="text-align:center;">
                <a asp-action="Index" asp-route-sortOrder="@ViewData["AuthorSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Authors</a>
            </th>
            <th style="text-align:center;">
                Genre
            </th>
            <th style="text-align:center;">
                Year Published
            </th>
            <th style="text-align:center;">
                ISBN 10
            </th>
            <th style="text-align:center;">
                ISBN 13
            </th>
            <th style="text-align:center;">
                Rating
            </th>
        </tr>
    </thead>
    <tbody>

@*Fetches each book image from the database to display on the page also controls the size of the images*@
@foreach (var item in Model) {
        <tr>
            <td>
                    @* If the book has an image attached, take the Cover byte array and convert it into an image. If there is no image, keep the space, but don't display anything*@
                    @if (item.Cover != null)
                    {
                        <img id="cover" style="width:150px;height:220px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(item.Cover))">
                    }
                    else
                    {
                        <img id="cover" style="width:150px;height:200px; object-fit:cover" src="">
                    }
            </td>
           @* Fetches each book's information from the database to display*@
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Authors.Name)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.PublishYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN_10)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN_13)
            </td>
            <td style="text-align:center;">
                @* The view data comes from the index action and takes the average rating and the number rating for each book *@
                <p>@ViewData["AverageRating" + item.ISBN_13] (@ViewData["CountRating"+item.ISBN_13])</p>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.ISBN_13" style="margin-bottom: 2px" class="btn btn-primary">Details</a>
                <a asp-action="Edit" asp-route-id="@item.ISBN_13" style="margin-bottom: 2px; padding-left: 30px; padding-right: 30px;" class="btn btn-primary"> <i class="bi                    bi-pencil-square"></i></a>
                <a asp-action="Delete" asp-route-id="@item.ISBN_13" style="margin-bottom: 2px; padding-right: 30px; padding-left: 30px" class="btn btn-primary"> <i class="bi                   bi-trash-fill"></i></a>
                @* This should link to the Review controller to create a new review for this particular book and user. If the review already exists, then redirect to the Edit action *@
                <a asp-controller="Reviews" asp-action="Create" asp-route-Isbn_13="@item.ISBN_13"  style="margin-bottom: 2px" class="btn btn-primary">Review</a>
                <script>
                    loadFavorite(@item.ISBN_13)
                    //setTimeout(loadFavorite, 1000,@item.ISBN_13);
                </script>
                <div id="@("FavoriteButton" + item.ISBN_13)">
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.PreviousPage ? "disabled" : "";
    var nextDisabled = !Model.NextPage ? "disabled" : "";
    var doubleDisabled = Model.PageIndex + 2 <= Model.TotalPages ? "" : "disabled";
    var seePrev = !Model.PreviousPage ? "-" : $"{Model.PageIndex-1}";
    var seeNext = !Model.NextPage ? "-" : $"{Model.PageIndex+1}";
    var seeDouble = Model.PageIndex + 2 <= Model.TotalPages ? $"{Model.PageIndex+2}" : "-";
}

<p style="margin-bottom:25px">Currently on page @(Model.PageIndex) of @(Model.TotalPages)</p>
<a asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]"
        asp-route-pageNumber="1"
        asp-route-currentFilter="@ViewData["CurrentFilter"]"
        class="btn btn-default @prevDisabled"
        style="margin-bottom:25px; outline-color: grey">
        First
</a>
<a
    asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]"
        asp-route-pageNumber="@(Model.PageIndex-1)"
        asp-route-currentFilter="@ViewData["CurrentFilter"]"
        class="btn btn-default @prevDisabled"
        style="margin-bottom:25px; outline-color: grey">
        @seePrev
</a>
<a
        class="btn btn-default"
        style="margin-bottom:25px; color: blue; outline-color: blue; background-color: gray;">
        @(Model.PageIndex)
</a>
<a 
    asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]"
        asp-route-pageNumber="@(Model.PageIndex+1)"
        asp-route-currentFilter="@ViewData["CurrentFilter"]"
        class="btn btn-default @nextDisabled"
        style="margin-bottom:25px; outline-color: grey">
        @seeNext
</a>
<a 
    asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]"
        asp-route-pageNumber="@(Model.PageIndex+2)"
        asp-route-currentFilter="@ViewData["CurrentFilter"]"
        class="btn btn-default @doubleDisabled"
        style="margin-bottom:25px; outline-color: grey">
        @seeDouble
</a>
<a asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]"
        asp-route-pageNumber="@(Model.TotalPages)"
        asp-route-currentFilter="@ViewData["CurrentFilter"]"
        class="btn btn-default @nextDisabled"
        style="margin-bottom:25px; outline-color: grey">
        Last
</a>