SocialLibraryMVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialLibraryMVC.Data;
using SocialLibraryMVC.Models;
using ImageMagick;
using System.Security.Claims;

namespace SocialLibraryMVC.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Books
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            //Get the way the data should be sorted from UI
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AuthorSortParm"] = sortOrder == "Author" ? "auther_desc" : "Author";
            var applicationDbContext = _context.Books.Include(b => b.Authors);
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["currentFilter"] = searchString;

            //If the search bar has information display only books with title's containing the query.
            if (!String.IsNullOrEmpty(searchString))
            {
                switch (sortOrder)
                {
                    case "name_desc":
                        applicationDbContext = _context.Books.OrderByDescending(b => b.Title).Where(b => b.Title.Contains(searchString)).Include(b => b.Authors);
                        break;
                    case "Author":
                        applicationDbContext = _context.Books.OrderBy(b => b.Authors).Where(b => b.Title.Contains(searchString)).Include(b => b.Authors);
                        break;
                    case "author_desc":
                        applicationDbContext = _context.Books.OrderByDescending(b => b.Authors).Where(b => b.Title.Contains(searchString)).Include(b => b.Authors);
                        break;
                    default:
                        applicationDbContext = _context.Books.OrderBy(b => b.Title).Where(b => b.Title.Contains(searchString)).Include(b => b.Authors);
                        break;
                }
            }
            //Otherwise just take the current order, default is Title alphabetically.
            else
            {
                switch (sortOrder)
                {
                    case "name_desc":
                        applicationDbContext = _context.Books.OrderByDescending(b => b.Title).Include(b => b.Authors);
                        break;
                    case "Author":
                        applicationDbContext = _context.Books.OrderBy(b => b.Authors).Include(b => b.Authors);
                        break;
                    case "author_desc":
                        applicationDbContext = _context.Books.OrderByDescending(b => b.Authors).Include(b => b.Authors);
                        break;
                    default:
                        applicationDbContext = _context.Books.OrderBy(b => b.Title).Include(b => b.Authors);
                        break;
                }
            }

            // This to find the average and total reviews and add them to the ViewData for each book 
            foreach (var book in applicationDbContext)
            {
                var reviews = _context.Reviews.Where(r => r.Isbn_13 == book.ISBN_13);
                int sumRating = 0;
                foreach (var review in reviews)
                {
                    sumRating += review.Rating;
                }
                ViewData["AverageRating"+book.ISBN_13] = (reviews.Count()>0)?((double)sumRating / reviews.Count()) : 0;
                ViewData["CountRating"+book.ISBN_13] = reviews.Count();
            }

            ViewBag.Favorites = null;
            string? user_id = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            //if (user_id != null)
                //ViewBag.Favorites = _context.UserFavorites.Where(f => f.User_id == User.FindFirst(ClaimTypes.NameIdentifier).Value).ToList();
            return View(await PaginatedList<Book>.CreateAsync(applicationDbContext, pageNumber ?? 1, 10));
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = await _context.Books
                .Include(b => b.Authors)
                .FirstOrDefaultAsync(m => m.ISBN_13 == id);
            if (books == null)
            {
                return NotFound();
            }

            ViewBag.Cover = null;
            if (books.Cover != null)
                ViewBag.Cover = books.Cover;

            return View(books);
        }

        // GET: Books/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Bind("Title,Description,AuthorId,Genre,PublishYear,ISBN_10,ISBN_13,Cover")] Books books
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Title,Description,AuthorId,Genre,PublishYear,ISBN_10,ISBN_13,Cover")] Book books)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();

                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);

                        // Magick.NET to resize the image if its too big
                        if (dataStream.Length > 50000)
                        {
                            dataStream.Position = 0;
                            var image = new MagickImage(dataStream);
                            // 300 by 500 is bigger than what the website displays, but this is for a better quality image
                            var size = new MagickGeometry(300, 500);
                            image.Resize(size);
                            books.Cover = image.ToByteArray();
                        }
                        // If the image is small enough, then keep the original size
                        else
                        {
                            books.Cover = dataStream.ToArray();
                        }
                    }
                }
                _context.Add(books);
                await _context.SaveChangesAsync();
                TempData["success"] = "Book added successfully!!"; //Toastr
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", books.AuthorId);
            return View(books);

        }

        // GET: Books/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = await _context.Books.FindAsync(id);
            if (books == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", books.AuthorId);
            // This viewbag is for the image display
            ViewBag.Cover = null;
            if(books.Cover != null)
                ViewBag.Cover = books.Cover;
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(long id, [Bind("Title,Description,AuthorId,Genre,PublishYear,ISBN_10,ISBN_13")] Book books)
        {
            if (id != books.ISBN_13)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // If there was an image uploaded, then put that image onto the books.Cover property
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);

                        if (dataStream.Length > 50000)
                        {
                            // Magick.NET to resize the image if its too big
                            dataStream.Position = 0;
                            var image = new MagickImage(dataStream);
                            var before = image.ToByteArray().Length; 
                            var size = new MagickGeometry(300, 500);
                            image.Resize(size);
                            var after = image.ToByteArray().Length;
                            books.Cover = image.ToByteArray();
                        }
                        else
                        {
                            books.Cover = dataStream.ToArray();
                        }
                    }
                }

SocialLibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialLibraryMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchJournal.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialLibraryMVC.styles.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">

    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <partial name="_Notifications" />
    <header>
        <!--
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SocialLibraryMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        -->

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Books" asp-action="Index">Social Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    @*
                  <a class="nav-link active" href="#">Home
                    <span class="visually-hidden">(current)</span>
                  </a>*@
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-controller="Books" asp-action="Index">Books</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-controller="Reviews" asp-action="Index">Recent Reviews</a>
                </li>
              </ul>
@*              <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>*@
              <partial name="_LoginPartial" />
            </div>
          </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <style>
        #footer {
            position: fixed;
            padding: 10px 10px 0px 10px;
            bottom: 0;
            width: 100%;
            height: 40px;
            background: white;
        }
    </style>
    <div id="footer">
        &copy; 2022 - SocialLibraryMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-dark">Privacy</a>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SocialLibraryMVC/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]'); 
    </script>
}

@if (TempData["failure"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["failure"]'); 
    </script>
}